env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:   
  no-console: off
  no-plusplus: off
  import/prefer-default-export: off
  indent: off
  linebreak-style: off
  # max-len: off
  # no-mixed-operators: off
  # no-param-reassign: off
  # camelcase: off
  # no-bitwise: off
  # new-cap: off
  # radix: off
  # func-names: off